# Generated by Django 3.0.8 on 2020-09-02 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100, null=True)),
                ('food_image', models.ImageField(default=0, upload_to='')),
                ('price', models.FloatField(default=0.0)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, choices=[('FR', 'Abia'), ('SO', 'Delta'), ('JR', 'Lagos'), ('SR', 'Bauchi'), ('GR', 'FCT')], default='FR', max_length=5)),
                ('user', models.OneToOneField(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_date', models.DateField()),
                ('expected_time', models.TimeField()),
                ('total_person', models.IntegerField(default=0)),
                ('message', models.TextField(max_length=200, null=True)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('restaurant', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='rapp.Restaurant')),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('date_ordered', models.DateField(default=django.utils.timezone.now)),
                ('order_completed', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(blank=True, max_length=200)),
                ('date_added', models.DateField(auto_now=True)),
                ('food_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rapp.Restaurant')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
