# Generated by Django 3.0.8 on 2020-10-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='User Name')),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('otp', models.CharField(default=374093, max_length=6)),
                ('phone_number', models.IntegerField(default=123)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
