# Generated by Django 3.0.8 on 2020-10-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='otp',
            field=models.CharField(default=87262, max_length=6),
        ),
    ]
