# Generated by Django 3.1 on 2020-09-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
