# Generated by Django 3.0.8 on 2020-09-09 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20200909_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catigories',
            old_name='categories1',
            new_name='Popular_category',
        ),
        migrations.RemoveField(
            model_name='catigories',
            name='categories',
        ),
        migrations.AddField(
            model_name='products',
            name='popular_categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Catigories'),
        ),
    ]
