# Generated by Django 3.0.8 on 2020-10-20 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unpaid_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_join', models.DateTimeField(default=django.utils.timezone.now)),
                ('capital', models.DecimalField(decimal_places=1, default=0, max_digits=500000)),
                ('amount_to_pay', models.DecimalField(decimal_places=1, default=0, max_digits=500000)),
                ('amount_merged', models.DecimalField(decimal_places=1, default=0, max_digits=500000)),
                ('merged_to_pay', models.BooleanField(default=False)),
                ('amount_payed', models.DecimalField(decimal_places=1, default=0, max_digits=500000)),
                ('payment_completed', models.BooleanField(default=False)),
                ('account_paying_to', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_join'],
            },
        ),
        migrations.CreateModel(
            name='PTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivers_id', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=1, default=0, max_digits=500000)),
                ('account_paying_to', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_capital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tradeapp.Unpaid_user')),
            ],
        ),
        migrations.CreateModel(
            name='Paid_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('date_paid', models.DateTimeField(default=django.utils.timezone.now)),
                ('interest', models.DecimalField(decimal_places=1, default=0, max_digits=500000)),
                ('amount_to_merge', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=500000, null=True)),
                ('amount_merged', models.DecimalField(decimal_places=1, default=0, max_digits=500000)),
                ('merged_to_receive', models.BooleanField(default=False)),
                ('receiving_from', models.CharField(blank=True, max_length=200, null=True)),
                ('received_completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_capital', models.DecimalField(decimal_places=1, default=0, max_digits=500000)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
