# Generated by Django 3.0.8 on 2020-08-01 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advanceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='school_name',
            new_name='schoolName',
        ),
    ]
