# Generated by Django 3.0.8 on 2020-08-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish_post',
            field=models.BooleanField(default=False),
        ),
    ]
