# Generated by Django 3.1 on 2020-08-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_publish_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publish_post',
        ),
        migrations.AddField(
            model_name='post',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
