# Generated by Django 3.1 on 2020-08-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200808_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
