# Generated by Django 3.1 on 2020-09-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20200908_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Al', 'All'), ('PP', 'Popular'), ('TD', 'Trending'), ('NA', 'New_arrival')], default='Al', max_length=30),
        ),
    ]
