# Generated by Django 3.0.8 on 2020-09-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catigories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Popular_category', models.CharField(choices=[('SP', 'Sport'), ('BT', 'Beauty'), ('EL', 'Electronic'), ('CM', 'Computer'), ('BY', 'Baby'), ('FS', 'Fashion')], default='Al', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.AlterField(
            model_name='products',
            name='product_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
