# Generated by Django 3.0.8 on 2020-09-09 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20200909_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catigories',
            old_name='Popular_category',
            new_name='categories1',
        ),
        migrations.AddField(
            model_name='catigories',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Products'),
        ),
    ]
