# Generated by Django 3.1 on 2020-09-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20200909_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='popular_categories',
        ),
        migrations.AddField(
            model_name='products',
            name='Popular_category',
            field=models.CharField(choices=[('SP', 'Sport'), ('BT', 'Beauty'), ('EL', 'Electronic'), ('CM', 'Computer'), ('BY', 'Baby'), ('FS', 'Fashion')], default='Al', max_length=30),
        ),
        migrations.DeleteModel(
            name='Catigories',
        ),
    ]
