# Generated by Django 3.1 on 2020-09-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_auto_20200909_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Popular_category',
            field=models.CharField(choices=[('Popolar_categories', (('Sport', 'Sport'), ('Sports', 'Sports')))], default='Al', max_length=30),
        ),
    ]
