# Generated by Django 3.1 on 2020-09-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_auto_20200909_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Popular_category',
        ),
        migrations.AddField(
            model_name='products',
            name='Cartegory',
            field=models.CharField(choices=[('POPULAR CATEGORIES', (('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Computer', 'Computer'), ('Beauty', 'Beauty'), ('Sport', 'Sport'))), ('TRENDING PRODUCTS', (('Top_10', 'Top_10'), ('Womens', 'Womens'), ('Mens', 'Mens'), ('Kids', 'Kids'), ('Accessories', 'Accessories')))], default='Al', max_length=30),
        ),
    ]
