# Generated by Django 3.1 on 2020-09-10 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0009_auto_20200909_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Cartegory',
            field=models.CharField(choices=[('POPULAR CATEGORIES', (('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Computer', 'Computer'), ('Beauty', 'Beauty'), ('Sport', 'Sport'))), ('TRENDING PRODUCTS', (('Top_10', 'Top_10'), ('Womens', 'Womens'), ('Mens', 'Mens'), ('Kids', 'Kids'), ('Accessories', 'Accessories'))), ('NEW ARRIVAL', (('Televisons', 'Top_10'), ('Computer', 'Computer'), ('Jewelry', 'Jewelry'), ('Apparel', 'Apparel'), ('Apparel', 'Apparel')))], default='Top_10', max_length=30),
        ),
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.products')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('ordered_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('orderitem', models.ManyToManyField(to='ecommerce.Orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
