# Generated by Django 3.1 on 2020-09-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_auto_20200910_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='Cartegory',
            field=models.CharField(choices=[('POPULAR CATEGORIES', (('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Computer', 'Computer'), ('Beauty', 'Beauty'), ('Sport', 'Sport'))), ('TRENDING PRODUCTS', (('Top_10', 'Top_10'), ('Womens', 'Womens'), ('Mens', 'Mens'), ('Kids', 'Kids'), ('Accessories', 'Accessories'))), ('NEW ARRIVAL', (('Televisons', 'Televisons'), ('Computer', 'Computer'), ('Jewelry', 'Jewelry'), ('Apparel', 'Apparel'), ('Apparel', 'Apparel')))], default='Top_10', max_length=30),
        ),
    ]
