# Generated by Django 3.1 on 2020-09-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_myuser_date_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='has_got_mail',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='date_join',
            field=models.DateField(),
        ),
    ]
