# Generated by Django 3.0.8 on 2020-10-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userwallet', '0004_auto_20201008_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='account_number',
            field=models.IntegerField(default='7715611928'),
        ),
    ]
