# Generated by Django 3.1 on 2020-10-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userwallet', '0005_auto_20201008_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='account_number',
            field=models.IntegerField(default='7714963933'),
        ),
    ]
