# Generated by Django 3.1 on 2020-10-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userwallet', '0006_auto_20201008_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='account_number',
            field=models.IntegerField(default='7716780802'),
        ),
    ]
