# Generated by Django 3.1 on 2020-10-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userwallet', '0007_auto_20201008_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='account_number',
            field=models.IntegerField(default='7716921425'),
        ),
    ]
