# Generated by Django 3.1 on 2020-10-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userwallet', '0008_auto_20201008_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='account_number',
            field=models.IntegerField(default='7714249582'),
        ),
    ]
