# Generated by Django 3.1 on 2020-10-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userwallet', '0009_auto_20201009_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='account_number',
            field=models.IntegerField(default='7714065008'),
        ),
    ]
