# Generated by Django 3.0.8 on 2020-10-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userwallet', '0011_auto_20201009_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='account_number',
            field=models.IntegerField(default='7716430987'),
        ),
    ]
