# Generated by Django 3.1.2 on 2020-10-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userwallet', '0012_auto_20201009_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='account_number',
            field=models.IntegerField(default='7711873372'),
        ),
    ]
