# Generated by Django 3.1.2 on 2020-10-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userwallet', '0013_auto_20201021_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='account_number',
            field=models.IntegerField(default='7711446786'),
        ),
    ]
