# Generated by Django 3.1 on 2020-09-11 22:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='assets/product')),
                ('product_description', models.TextField(blank=True, max_length=200, null=True)),
                ('rating', models.IntegerField(blank=True, default=1, null=True)),
                ('price', models.FloatField(default=0, null=True)),
                ('Cartegory', models.CharField(choices=[('POPULAR CATEGORIES', (('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Computer', 'Computer'), ('Beauty', 'Beauty'), ('Sport', 'Sport'))), ('TRENDING PRODUCTS', (('Top_10', 'Top 10'), ('Womens', 'Womens'), ('Mens', 'Mens'), ('Kids', 'Kids'), ('Accessories', 'Accessories'))), ('NEW ARRIVAL', (('Televisons', 'Televisons'), ('Computer', 'Computer'), ('Jewelry', 'Jewelry'), ('Apparel', 'Apparel'), ('Apparel', 'Apparel')))], default='Top_10', max_length=30)),
                ('slug', models.SlugField(blank=True, help_text='Please put a url name', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.products')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('ordered_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('orderitem', models.ManyToManyField(to='ecommerce.Orderitem')),
            ],
        ),
    ]
