# Generated by Django 3.0.8 on 2020-09-16 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_auto_20200916_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='myuser',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='quantity',
            new_name='user_quantity',
        ),
    ]
