# Generated by Django 3.1 on 2020-09-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_auto_20200917_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
