# Generated by Django 3.1 on 2020-09-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_auto_20200919_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
