# Generated by Django 3.1 on 2020-10-04 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_auto_20201004_0720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='rated',
        ),
    ]
