# Generated by Django 3.0.8 on 2020-10-07 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_auto_20201004_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='ratin',
        ),
        migrations.CreateModel(
            name='SubImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='assets/product')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='assets/product')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='assets/product')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='assets/product')),
                ('img', models.ImageField(blank=True, null=True, upload_to='assets/product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Products')),
            ],
        ),
    ]
