# Generated by Django 3.0.8 on 2020-10-08 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
