# Generated by Django 3.1 on 2020-10-08 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0028_auto_20201008_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviews',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.products'),
        ),
    ]
