# Generated by Django 3.0.8 on 2020-10-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0032_productreviews_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
