# Generated by Django 3.0.8 on 2020-09-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_myuser_date_join'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='date_join',
        ),
        migrations.AddField(
            model_name='myuser',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
