# Generated by Django 3.1 on 2020-09-19 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200907_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='date_join',
        ),
    ]
